# Generated by Django 3.2.4 on 2021-06-30 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=150)),
                ('date', models.DateField(default=datetime.datetime(2021, 6, 30, 16, 1, 16, 761628))),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('adress_text', models.CharField(max_length=120)),
                ('adress_google', models.CharField(max_length=36)),
                ('star_rate', models.FloatField()),
            ],
        ),
    ]
