# Generated by Django 3.2.4 on 2021-06-30 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 30, 16, 3, 22, 286369)),
        ),
    ]
