# Generated by Django 3.2.4 on 2021-07-01 09:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_auto_20210701_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 1, 14, 44, 31, 460778)),
        ),
        migrations.AlterField(
            model_name='services',
            name='dates',
            field=models.DateField(default=datetime.datetime(2021, 7, 1, 14, 44, 31, 460778)),
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_room', models.IntegerField()),
                ('quantity_lux_room', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.services')),
            ],
        ),
    ]
