# Generated by Django 3.2.4 on 2021-07-01 10:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_auto_20210701_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='quantity_lux_room',
        ),
        migrations.AddField(
            model_name='rooms',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rooms',
            name='type_room',
            field=models.CharField(choices=[('default', 'Обычный'), ('lux', 'Люкс')], default=10, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotels',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 1, 15, 38, 53, 663583)),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='quantity_room',
            field=models.CharField(choices=[('1X', 'Одноместный'), ('2X', 'Двухместный'), ('3X', 'Трёхместный'), ('4X', 'Четерёхместный')], max_length=20),
        ),
        migrations.AlterField(
            model_name='services',
            name='dates',
            field=models.DateField(default=datetime.datetime(2021, 7, 1, 15, 38, 53, 663583)),
        ),
        migrations.CreateModel(
            name='description_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('refrigerator', models.BooleanField(default=False)),
                ('shower', models.BooleanField(default=False)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.rooms')),
            ],
        ),
    ]
