# Generated by Django 3.2.4 on 2021-07-01 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_auto_20210701_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotels',
            options={'verbose_name': 'Гостиница', 'verbose_name_plural': 'Гостиницы'},
        ),
        migrations.AlterField(
            model_name='hotels',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 1, 15, 56, 57, 580883)),
        ),
        migrations.AlterField(
            model_name='services',
            name='dates',
            field=models.DateField(default=datetime.datetime(2021, 7, 1, 15, 56, 57, 581882)),
        ),
    ]
