# Generated by Django 3.2.4 on 2021-07-01 12:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_auto_20210701_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='description_list',
            options={'verbose_name': 'Описание номер', 'verbose_name_plural': '4.Описании номера'},
        ),
        migrations.AlterModelOptions(
            name='hotels',
            options={'verbose_name': 'Гостиница', 'verbose_name_plural': '1.Гостиницы'},
        ),
        migrations.AlterModelOptions(
            name='rooms',
            options={'verbose_name': 'Номер', 'verbose_name_plural': '3.Номера'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Сервис', 'verbose_name_plural': '2.Сервисы'},
        ),
        migrations.AddField(
            model_name='rooms',
            name='hotel',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='hotels.hotels'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotels',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 1, 17, 30, 44, 21461)),
        ),
        migrations.AlterField(
            model_name='services',
            name='dates',
            field=models.DateField(default=datetime.datetime(2021, 7, 1, 17, 30, 44, 22461)),
        ),
    ]
