# Generated by Django 3.2.4 on 2021-07-02 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_auto_20210701_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 2, 11, 9, 19, 50103)),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='star_rate',
            field=models.FloatField(default=1),
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
