# Generated by Django 3.2.4 on 2021-07-02 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_auto_20210702_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 2, 12, 11, 23, 977182)),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='quantity_room',
            field=models.CharField(choices=[('1', 'Одноместный'), ('2', 'Двухместный'), ('3', 'Трёхместный'), ('4', 'Четерёхместный')], max_length=20),
        ),
    ]
