# Generated by Django 3.2.4 on 2021-07-06 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0012_auto_20210702_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description_list',
            old_name='shower',
            new_name='Baby_safety_gates',
        ),
        migrations.AddField(
            model_name='description_list',
            name='Board_games_puzzles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='description_list',
            name='Clothes_rack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='description_list',
            name='Desk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='description_list',
            name='Extra_long_beds',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='description_list',
            name='Heating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='description_list',
            name='Iron',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='description_list',
            name='Walk_in_closet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='description_list',
            name='radio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='description_list',
            name='sauna',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 6, 18, 15, 17, 230696)),
        ),
    ]
