# Generated by Django 3.2.4 on 2021-07-06 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_auto_20210706_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 6, 18, 15, 33, 883165)),
        ),
    ]
