# Generated by Django 3.2.4 on 2021-07-07 06:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0014_alter_hotels_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='Bar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotels',
            name='Fitnes_Club',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 7, 11, 52, 24, 106044)),
        ),
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=40)),
                ('LastName', models.CharField(max_length=40)),
                ('Passport_Serial', models.CharField(default='AA', max_length=4)),
                ('Passport_Number', models.IntegerField(default=1234567)),
                ('Guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.description_list')),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': '4.ФИО Госты',
            },
        ),
    ]
