# Generated by Django 3.2.4 on 2021-07-07 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0016_auto_20210707_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guests',
            old_name='Guest',
            new_name='hotel_name_number',
        ),
        migrations.RemoveField(
            model_name='guests',
            name='date1',
        ),
        migrations.RemoveField(
            model_name='guests',
            name='date2',
        ),
        migrations.AddField(
            model_name='guests',
            name='date_from',
            field=models.DateField(default=datetime.date(2021, 7, 7)),
        ),
        migrations.AddField(
            model_name='guests',
            name='date_to',
            field=models.DateField(default=datetime.date(2021, 7, 8)),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='date',
            field=models.DateField(default=datetime.date(2021, 7, 7)),
        ),
    ]
